### ISSUE TITLE
Hey there 

### ISSUE THREAD

**Issue by Haroenv** [devdreamsolution/devdreamsolution#6]
I couldn’t find another way to contact you, and I have a question. What’s up with all the reviewing?

**Comment by devdreamsolution** [comment]
hi @Haroenv 
https://join.skype.com/invite/kz16eAu91s8Y
what does that (all the reviewing) mean?

**Comment by devdreamsolution** [comment]
i was reviewing your open source. don't worry i will not write anymore.

**Comment by Haroenv** [comment]
no worries at all, I was just wondering if it might have been automated, since there were so many at once
